compParamDict = dict()
compRangeDict = dict()
porosity = dict()
porosityRange = dict()
solverChoices = ['Lin']
lossFunctionChoices = ['Simple', 'Squares', 'LogSimple', 'LogSquares']
lv2LossFunctionVals = dict()
lv1LossFunctionVal = dict()
index = dict()
lossFunctionProgress = dict()
